AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.

Resources:
  AuthorizeUser:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: Ponder-AuthorizeUser
      Handler: authorizers/authorizeruser.handler
      Runtime: nodejs8.10
      CodeUri: s3://ponder-code/ponder-latest.zip
      Description: ''
      MemorySize: 128
      Timeout: 3
      Role: 'arn:aws:iam::478373966066:role/LambdaServiceRole'

  GetTopDecisions:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: Ponder-GetMyDecisions
      Handler: functions/getmydecisions.handler
      Runtime: nodejs8.10
      CodeUri: s3://ponder-code/ponder-latest.zip
      Description: ''
      MemorySize: 128
      Timeout: 3
      Role: 'arn:aws:iam::478373966066:role/LambdaServiceRole'
      Events:
        Schedule1:
          Type: Schedule
          Properties:
            Schedule: rate(15 minutes)
            Input: '{ "context" : { "authorizer-principal-id": 1}, "is-ping": true }'     
      VpcConfig:
        SecurityGroupIds:
          - sg-0594f0e78619424b3
        SubnetIds:
          - subnet-c89e10e6
          - subnet-e54b0eea

  LoginUser:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: Ponder-LoginUser
      Handler: functions/login.handler
      Runtime: nodejs8.10
      CodeUri: s3://ponder-code/ponder-latest.zip
      Description: ''
      MemorySize: 128
      Timeout: 3
      Role: 'arn:aws:iam::478373966066:role/LambdaServiceRole'
      Events:
        Schedule1:
          Type: Schedule
          Properties:
            Schedule: rate(15 minutes)
            Input: '{ "Email": "dedlow10@gmail.com", "Password": "MyAwesomePassword123" }'
      VpcConfig:
        SecurityGroupIds:
          - sg-0594f0e78619424b3
        SubnetIds:
          - subnet-61ae223d
          - subnet-c89e10e6















