AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.

Resources:
  DecisionMakerAPI:
    Name: DecisionMakerAPI
    Type: AWS::Serverless::Api
    Properties:
      DefinitionUri: s3://ponder-code/Ponder-Cloudformation/ponder-api.yml
      StageName: prod

  AcceptInvitation:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: Ponder-AcceptInvitation
      Handler: functions/acceptinvitation.handler
      Runtime: nodejs8.10
      CodeUri: s3://ponder-code/ponder-latest.zip
      Description: ''
      MemorySize: 128
      Timeout: 3
      Role: 'arn:aws:iam::478373966066:role/LambdaServiceRole'
      Events:
        Schedule1:
          Type: Schedule
          Properties:
            Schedule: rate(15 minutes)
            Input: '{ "context" : { "authorizer-principal-id": 1}, "is-ping": true }'
        Api1:
          Type: Api
          Properties:
            RestApiId: !Ref DecisionMakerAPI
            Path: /friends/invitations
            Method: POST
      VpcConfig:
        SecurityGroupIds:
          - sg-0594f0e78619424b3
        SubnetIds:
          - subnet-c89e10e6
          - subnet-e54b0eea

  AddFriend:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: Ponder-AddFriend
      Handler: functions/addfriend.handler
      Runtime: nodejs8.10
      CodeUri: s3://ponder-code/ponder-latest.zip
      Description: ''
      MemorySize: 128
      Timeout: 3
      Role: 'arn:aws:iam::478373966066:role/LambdaServiceRole'
      Events:
        Schedule1:
          Type: Schedule
          Properties:
            Schedule: rate(15 minutes)
            Input: '{ "context" : { "authorizer-principal-id": 1}, "is-ping": true }'
        Api1:
          Type: Api
          Properties:
            RestApiId: !Ref DecisionMakerAPI
            Path: /friends
            Method: POST
      VpcConfig:
        SecurityGroupIds:
          - sg-0594f0e78619424b3
        SubnetIds:
          - subnet-c89e10e6
          - subnet-e54b0eea

  AuthorizeUser:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: Ponder-AuthorizeUser
      Handler: authorizers/authorizeruser.handler
      Runtime: nodejs8.10
      CodeUri: s3://ponder-code/ponder-latest.zip
      Description: ''
      MemorySize: 128
      Timeout: 3
      Role: 'arn:aws:iam::478373966066:role/LambdaServiceRole'
      Events:
        Api1:
          Type: Api
          Properties:
            RestApiId: !Ref DecisionMakerAPI
            Path: /MyResource
            Method: ANY

  CountMyDecisionVotes:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: Ponder-CountMyDecisionVotes
      Handler: functions/countmydecisionvotes.handler
      Runtime: nodejs8.10
      CodeUri: s3://ponder-code/ponder-latest.zip
      Description: ''
      MemorySize: 128
      Timeout: 3
      Role: 'arn:aws:iam::478373966066:role/LambdaServiceRole'
      Events:
        Api1:
          Type: Api
          Properties:
            RestApiId: !Ref DecisionMakerAPI
            Path: /votes/me/count
            Method: GET
      VpcConfig:
        SecurityGroupIds:
          - sg-0594f0e78619424b3
        SubnetIds:
          - subnet-c89e10e6
          - subnet-e54b0eea

  CountMyDecisions:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: Ponder-CountMyDecisions
      Handler: functions/countmydecisions.handler
      Runtime: nodejs8.10
      CodeUri: s3://ponder-code/ponder-latest.zip
      Description: ''
      MemorySize: 128
      Timeout: 3
      Role: 'arn:aws:iam::478373966066:role/LambdaServiceRole'
      Events:
        Api1:
          Type: Api
          Properties:
            RestApiId: !Ref DecisionMakerAPI
            Path: /decisions/me/count
            Method: GET
      VpcConfig:
        SecurityGroupIds:
          - sg-0594f0e78619424b3
        SubnetIds:
          - subnet-c89e10e6
          - subnet-e54b0eea

  CreateDecision:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: Ponder-CreateDecision
      Handler: functions/createdecision.handler
      Runtime: nodejs8.10
      CodeUri: s3://ponder-code/ponder-latest.zip
      Description: ''
      MemorySize: 128
      Timeout: 3
      Role: 'arn:aws:iam::478373966066:role/LambdaServiceRole'
      Events:
        Schedule1:
          Type: Schedule
          Properties:
            Schedule: rate(15 minutes)
            Input: '{ "context" : { "authorizer-principal-id": 1}, "is-ping": true }'
        Api1:
          Type: Api
          Properties:
            RestApiId: !Ref DecisionMakerAPI
            Path: /decisions
            Method: POST                        
      VpcConfig:
        SecurityGroupIds:
          - sg-0594f0e78619424b3
        SubnetIds:
          - subnet-c89e10e6
          - subnet-e54b0eea

  DeleteDecision:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: Ponder-DeleteDecision
      Handler: functions/deletedecision.handler
      Runtime: nodejs8.10
      CodeUri: s3://ponder-code/ponder-latest.zip
      Description: ''
      MemorySize: 128
      Timeout: 3
      Role: 'arn:aws:iam::478373966066:role/LambdaServiceRole'
      Events:
        Api1:
          Type: Api
          Properties:
            RestApiId: !Ref DecisionMakerAPI
            Path: '/decisions/{id}'
            Method: DELETE      
      VpcConfig:
        SecurityGroupIds:
          - sg-0594f0e78619424b3
        SubnetIds:
          - subnet-c89e10e6
          - subnet-e54b0eea

  DeleteFriend:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: Ponder-DeleteFriend
      Handler: functions/deletefriend.handler
      Runtime: nodejs8.10
      CodeUri: s3://ponder-code/ponder-latest.zip
      Description: ''
      MemorySize: 128
      Timeout: 3
      Role: 'arn:aws:iam::478373966066:role/LambdaServiceRole'
      Events:
        Api1:
          Type: Api
          Properties:
            RestApiId: !Ref DecisionMakerAPI  
            Path: /friends
            Method: DELETE      
      VpcConfig:
        SecurityGroupIds:
          - sg-0594f0e78619424b3
        SubnetIds:
          - subnet-c89e10e6
          - subnet-e54b0eea

  FindUsers:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: Ponder-FindUsers
      Handler: functions/findusers.handler
      Runtime: nodejs8.10
      CodeUri: s3://ponder-code/ponder-latest.zip
      Description: ''
      MemorySize: 128
      Timeout: 3
      Role: 'arn:aws:iam::478373966066:role/LambdaServiceRole'
      Events:
        Schedule1:
          Type: Schedule
          Properties:
            Schedule: rate(15 minutes)
            Input: '{ "context" : { "authorizer-principal-id": 1}, "is-ping": true }'
        Api1:
          Type: Api
          Properties:
            RestApiId: !Ref DecisionMakerAPI
            Path: /users
            Method: GET            
      VpcConfig:
        SecurityGroupIds:
          - sg-0594f0e78619424b3
        SubnetIds:
          - subnet-c89e10e6
          - subnet-e54b0eea

  GetDecisionById:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: Ponder-GetDecisionById
      Handler: functions/getdecisionbyid.handler
      Runtime: nodejs8.10
      CodeUri: s3://ponder-code/ponder-latest.zip
      Description: ''
      MemorySize: 128
      Timeout: 3
      Role: 'arn:aws:iam::478373966066:role/LambdaServiceRole'
      Events:
        Api1:
          Type: Api
          Properties:
            RestApiId: !Ref DecisionMakerAPI
            Path: '/decisions/{id}'
            Method: GET      
      VpcConfig:
        SecurityGroupIds:
          - sg-0594f0e78619424b3
        SubnetIds:
          - subnet-c89e10e6
          - subnet-e54b0eea

  GetFriendInvitations:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: Ponder-GetFriendInvitations
      Handler: functions/getfriendinvitations.handler
      Runtime: nodejs8.10
      CodeUri: s3://ponder-code/ponder-latest.zip
      Description: ''
      MemorySize: 128
      Timeout: 3
      Role: 'arn:aws:iam::478373966066:role/LambdaServiceRole'
      Events:
        Schedule1:
          Type: Schedule
          Properties:
            Schedule: rate(15 minutes)
            Input: '{ "context" : { "authorizer-principal-id": 1}, "is-ping": true }'
        Api1:
          Type: Api
          Properties:
            RestApiId: !Ref DecisionMakerAPI
            Path: /friends/invitations
            Method: GET            
      VpcConfig:
        SecurityGroupIds:
          - sg-0594f0e78619424b3
        SubnetIds:
          - subnet-c89e10e6
          - subnet-e54b0eea

  GetFriends:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: Ponder-GetFriends
      Handler: functions/getfriends.handler
      Runtime: nodejs8.10
      CodeUri: s3://ponder-code/ponder-latest.zip
      Description: ''
      MemorySize: 128
      Timeout: 3
      Role: 'arn:aws:iam::478373966066:role/LambdaServiceRole'
      Events:
        Schedule1:
          Type: Schedule
          Properties:
            Schedule: rate(15 minutes)
            Input: '{ "context" : { "authorizer-principal-id": 1}, "is-ping": true }'
        Api1:
          Type: Api
          Properties:
            RestApiId: !Ref DecisionMakerAPI
            Path: /friends
            Method: GET            
      VpcConfig:
        SecurityGroupIds:
          - sg-0594f0e78619424b3
        SubnetIds:
          - subnet-c89e10e6
          - subnet-e54b0eea

  GetFriendsDecisions:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: Ponder-GetFriendsDecisions
      Handler: functions/getfriendsdecisions.handler
      Runtime: nodejs8.10
      CodeUri: s3://ponder-code/ponder-latest.zip
      Description: ''
      MemorySize: 128
      Timeout: 3
      Role: 'arn:aws:iam::478373966066:role/LambdaServiceRole'
      Events:
        Schedule1:
          Type: Schedule
          Properties:
            Schedule: rate(15 minutes)
            Input: '{ "context" : { "authorizer-principal-id": 1}, "is-ping": true }'
        Api1:
          Type: Api
          Properties:
            RestApiId: !Ref DecisionMakerAPI   
            Path: /decisions/friends
            Method: GET            
      VpcConfig:
        SecurityGroupIds:
          - sg-0594f0e78619424b3
        SubnetIds:
          - subnet-c89e10e6
          - subnet-e54b0eea

  GetMyDecisions:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: Ponder-GetMyDecisions
      Handler: functions/getmydecisions.handler
      Runtime: nodejs8.10
      CodeUri: s3://ponder-code/ponder-latest.zip
      Description: ''
      MemorySize: 128
      Timeout: 3
      Role: 'arn:aws:iam::478373966066:role/LambdaServiceRole'
      Events:
        Schedule1:
          Type: Schedule
          Properties:
            Schedule: rate(15 minutes)
            Input: '{ "context" : { "authorizer-principal-id": 1}, "is-ping": true }'
        Api1:
          Type: Api
          Properties:
            RestApiId: !Ref DecisionMakerAPI
            Path: /decisions/me
            Method: GET            
      VpcConfig:
        SecurityGroupIds:
          - sg-0594f0e78619424b3
        SubnetIds:
          - subnet-c89e10e6
          - subnet-e54b0eea

  GetTopDecisions:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: Ponder-GetTopDecisions
      Handler: functions/gettopdecisions.handler
      Runtime: nodejs8.10
      CodeUri: s3://ponder-code/ponder-latest.zip
      Description: ''
      MemorySize: 128
      Timeout: 3
      Role: 'arn:aws:iam::478373966066:role/LambdaServiceRole'
      Events:
        Schedule1:
          Type: Schedule
          Properties:
            Schedule: rate(15 minutes)
            Input: '{ "context" : { "authorizer-principal-id": 1}, "is-ping": true }'
        Api1:
          Type: Api
          Properties:
            RestApiId: !Ref DecisionMakerAPI  
            Path: /decisions/top
            Method: GET            
      VpcConfig:
        SecurityGroupIds:
          - sg-0594f0e78619424b3
        SubnetIds:
          - subnet-c89e10e6
          - subnet-e54b0eea

  GetUserById:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: Ponder-GetUserById
      Handler: functions/getuserbyid.handler
      Runtime: nodejs8.10
      CodeUri: s3://ponder-code/ponder-latest.zip
      Description: ''
      MemorySize: 128
      Timeout: 3
      Role: 'arn:aws:iam::478373966066:role/LambdaServiceRole'
      Events:
        Schedule1:
          Type: Schedule
          Properties:
            Schedule: rate(15 minutes)
        Api1:
          Type: Api
          Properties:
            RestApiId: !Ref DecisionMakerAPI 
            Path: '/users/{id}'
            Method: GET            
      VpcConfig:
        SecurityGroupIds:
          - sg-0594f0e78619424b3
        SubnetIds:
          - subnet-c89e10e6
          - subnet-e54b0eea

  GetVotesForDecision:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: Ponder-GetVotesForDecision
      Handler: functions/getvotesfordecision.handler
      Runtime: nodejs8.10
      CodeUri: s3://ponder-code/ponder-latest.zip
      Description: ''
      MemorySize: 128
      Timeout: 3
      Role: 'arn:aws:iam::478373966066:role/LambdaServiceRole'
      Events:
        Schedule1:
          Type: Schedule
          Properties:
            Schedule: rate(15 minutes)
            Input: '{ "params" : { "path": { "id": 1 } } }'
        Api1:
          Type: Api
          Properties:
            RestApiId: !Ref DecisionMakerAPI   
            Path: '/decisions/{id}/votes'
            Method: GET            
      VpcConfig:
        SecurityGroupIds:
          - sg-0594f0e78619424b3
        SubnetIds:
          - subnet-61ae223d
          - subnet-c89e10e6

  LoginUser:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: Ponder-LoginUser
      Handler: functions/login.handler
      Runtime: nodejs8.10
      CodeUri: s3://ponder-code/ponder-latest.zip
      Description: ''
      MemorySize: 128
      Timeout: 3
      Role: 'arn:aws:iam::478373966066:role/LambdaServiceRole'
      Events:
        Schedule1:
          Type: Schedule
          Properties:
            Schedule: rate(15 minutes)
            Input: '{ "Email": "dedlow10@gmail.com", "Password": "MyAwesomePassword123" }'
        Api1:
          Type: Api
          Properties:
            RestApiId: !Ref DecisionMakerAPI   
            Path: /users/login
            Method: POST
      VpcConfig:
        SecurityGroupIds:
          - sg-0594f0e78619424b3
        SubnetIds:
          - subnet-61ae223d
          - subnet-c89e10e6

  RegisterDeviceToken:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: Ponder-RegisterDeviceToken
      Handler: functions/registerdevicetoken.handler
      Runtime: nodejs8.10
      CodeUri: s3://ponder-code/ponder-latest.zip
      Description: ''
      MemorySize: 128
      Timeout: 3
      Role: 'arn:aws:iam::478373966066:role/LambdaServiceRole'
      Events:
        Api1:
          Type: Api
          Properties:
            RestApiId: !Ref DecisionMakerAPI    
            Path: /users/device-token
            Method: POST      
      VpcConfig:
        SecurityGroupIds:
          - sg-0594f0e78619424b3
        SubnetIds:
          - subnet-c89e10e6
          - subnet-e54b0eea

  RegisterUser:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: Ponder-RegisterUser
      Handler: functions/register.handler
      Runtime: nodejs8.10
      CodeUri: s3://ponder-code/ponder-latest.zip
      Description: ''
      MemorySize: 192
      Timeout: 3
      Role: 'arn:aws:iam::478373966066:role/LambdaServiceRole'
      Events:
        Schedule1:
          Type: Schedule
          Properties:
            Schedule: rate(15 minutes)
            Input: '{ "context" : { "authorizer-principal-id": 1}, "is-ping": true }'
        Api1:
          Type: Api
          Properties:
            RestApiId: !Ref DecisionMakerAPI    
            Path: /users
            Method: POST            
      VpcConfig:
        SecurityGroupIds:
          - sg-0594f0e78619424b3
        SubnetIds:
          - subnet-61ae223d
          - subnet-c89e10e6

  UpdateUser:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: Ponder-UpdateUser
      Handler: functions/updateuser.handler
      Runtime: nodejs8.10
      CodeUri: s3://ponder-code/ponder-latest.zip
      Description: ''
      MemorySize: 128
      Timeout: 3
      Role: 'arn:aws:iam::478373966066:role/LambdaServiceRole'
      Events:
        Api1:
          Type: Api
          Properties:
            RestApiId: !Ref DecisionMakerAPI    
            Path: '/users/{id}'
            Method: POST      
      VpcConfig:
        SecurityGroupIds:
          - sg-0594f0e78619424b3
        SubnetIds:
          - subnet-c89e10e6
          - subnet-e54b0eea

  VoteDecision:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: Ponder-VoteDecision
      Handler: functions/votedecision.handler
      Runtime: nodejs8.10
      CodeUri: s3://ponder-code/ponder-latest.zip
      Description: ''
      MemorySize: 128
      Timeout: 3
      Role: 'arn:aws:iam::478373966066:role/LambdaServiceRole'
      Events:
        Schedule1:
          Type: Schedule
          Properties:
            Schedule: rate(15 minutes)
            Input: '{ "context" : { "authorizer-principal-id": 1}, "is-ping": true }'
        Api1:
          Type: Api
          Properties:
            RestApiId: !Ref DecisionMakerAPI
            Path: '/decisions/{id}/vote/{optionNum}'
            Method: POST            
      VpcConfig:
        SecurityGroupIds:
          - sg-0594f0e78619424b3
        SubnetIds:
          - subnet-c89e10e6
          - subnet-e54b0eea















