# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1

orbs:
  aws-s3: circleci/aws-s3@1.0.3

jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:8.10
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: sudo sed -i '/jessie-backports/d' /etc/apt/sources.list
      - run: sudo sed -i '/jessie-updates/d' /etc/apt/sources.list
      - run: sudo apt-get update
      - run: sudo apt-get -y install python3-pip
      - run: sudo apt-get -y install python3-pip
      - run: pip3 install awscli --upgrade --user
      - run: (cd ~/repo; zip -r ponder-latest.zip .;)

      - aws-s3/copy:
          from: ~/repo/ponder.yml
          to: 's3://ponder-code/Ponder-Cloudformation/ponder.yml'

      - aws-s3/copy:
          from: ~/repo/ponder-api.yml
          to: 's3://ponder-code/Ponder-Cloudformation/ponder-api.yml'

      - aws-s3/copy:
          from: ponder-latest.zip
          to: 's3://ponder-code/ponder-$MAJOR_VERSION_NUMBER.$CIRCLE_BUILD_NUM.zip'
      
      - run: aws cloudformation deploy --template-file ~/repo/ponder.yml --stack-name Ponder-Serverless --capabilities CAPABILITY_IAM --parameter-overrides BucketName=ponder-code CodeKey=ponder-$MAJOR_VERSION_NUMBER.$CIRCLE_BUILD_NUM.zip